url: proyectopinguica.gtocolabora.org
baseurl:

# Site settings
title: Pinguica
email: proyectopinguica@gtocolabora.org
description: "Somos un centro que crea programas de formación artística que contribuye a la reconstrucción del tejido social; favoreciendo la formación integral de los niños con el objetivo de sensibilizar y crear conciencia del contexto en el que viven, propiciando su desarrollo como agente de cambio para su entorno."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 89421C
  secondary: D12A2E
  secondary-dark: 511011

# Team names, titles and social links
people:

- name: Lucía Muñoz
  pic: lu
  position: Diagnósticos
  social:
    - title: twitter
      url: lu_spontanee
    - title: facebook
      url: https://www.facebook.com/LuXocoHuitzilli
    - title: email
      url: lu.huitzilli.xoco@gmail.com

- name: Erick Rocha
  pic: erick
  position: Marketing
  social:
    - title: twitter
      url: erick_tita
    - title: facebook
      url: https://www.facebook.com/erick.rochalarios
    - title: email
      url: abc.erick777@gmail.com

- name: Raúl Baena García
  pic: raul
  position: Relaciones Públicas
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/raul.baenagarcia
    - title: email
      url: raul.baena.g@gmail.com

- name: Lorena Urzúa
  pic: lore
  position: Diseño
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/lorena.urzua
    - title: email
      url: xihuitl.xihuitl@gmail.com

- name: Alina Guadalupe Pedroza López
  pic: alina
  position: Dirección
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/alina.pedroza.16
    - title: email
      url: alinagpe@gmail.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/ProyectoPinguica/
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/abcsds/Pinguica

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
